### ISSUE TITLE
How to validate Http get request with this ?

### ISSUE THREAD

**Issue by niroshana1234** [connorjburton/hmac-auth-express#17]

**Comment by connorjburton** [comment]
Hi, you shouldn't have to do anything special, this package is used daily with both GET and POST requests. What in particular are you having problems with, do you have any code to share?

**Comment by niroshana1234** [comment]
Https://example.com/getExercise?bookId=232&chapterId=12&ExId=30&digest=qshdkkqdhskhkadsadsadsd

I want to validate the above URL which will trigger when the user clicks on a browser link. So it does not contain authorization headers. Hmac is attached to the URL on a query param called digest. Intention is, the user should not be able to call the same request by changing the query params.

**Comment by connorjburton** [comment]
Thanks for that.  The package does not support parsing the HMAC digest from a GET parameter, only via the headers.

I would try and re-think how you are approaching this problem, I don't think HMAC is the best solution, ideally you should generating the HMAC digest at runtime, not creating a digest and hardcoding a URL (if that is what you are doing), you'd first run into issues with the replay attack prevention built into the package (see `maxInterval` and `minInterval`).

I assume the scenario is the URL is going to be on a server you don't have control over, therefore can't generate the HMAC digest at runtime? If so I don't think HMAC is any more secure than putting `&key=randomGenKey` in the URL and manually validating that when the request comes in with a key:value pair.

E.g

`'https://example.com/getExercise?bookId=232&chapterId=12&ExId=30': ['randomKey', 'randomKey2']`

If you do own the server that the URL will be hosted on and still want it to be a link then use the redirect method, set the URL to `serverurlishosted.com/redirect?url=https://example.com/getExercise?bookId=232&chapterId=12&ExId=30` and then on `serverurlishosted.com/redirect` generate the HMAC and redirect them to the destination with the digest in a header.

**Comment by niroshana1234** [comment]
Thank you very much for providing a solution to my problem. But my original get request is an XHR/Ajax call. So redirection will not work here.

**Comment by connorjburton** [comment]
No problem, if you want to message me to discuss futher then you can contact me on my email, I'd be happy to advise on a solution for your problem.
