### ISSUE TITLE
UNIX Timestamp in HMAC is expected to be (UNIX Timestamp / 1000), should be just UNIX Timestamp

### ISSUE THREAD

**Issue by connorjburton** [connorjburton/hmac-auth-express#2]
PR #3 

During writing tests, discovered a discrepancy between documentation and API. The documentation states to send the UNIX Timestamp as the first part of the HMAC Digest. The API actually expects the `(UNIX Timestamp / 1000)`.

This will be a breaking change (`4.0.0`) to look for a UNIX timestamp and divide it by 1000 in the middleware, rather than it expect it to be already converted.

- [x] Change code to expect un-mutated UNIX timestamp
- [x] Update `Readme.md` HMAC digest code example to reflect change
- [x] Update changelog
- [x] Write new section to migration guide
- [x] Update migration guide to reference the issue / PR relating to migration
- [x] Write tests

**Comment by connorjburton** [comment]
@timomeh tagging you as I know you use this package.

**Comment by timomeh** [comment]
Thanks for the info, I'm currently not using it in an active project
