### ISSUE TITLE
Remove JSON stringify

### ISSUE THREAD

**Issue by connorjburton** [connorjburton/hmac-auth-express#55]

**Comment by deanshelton913** [comment]
Bump.
JSON stringify is not guaranteed to be ordered if not an array. If its an object there could be a mismatch on valid data

**Comment by connorjburton** [comment]
@deanshelton913 I'll look into this soon

**Comment by connorjburton** [comment]
Hi @deanshelton913 if you are experiencing this bug, could you try out this PR for me please? https://github.com/cburton-godaddy/hmac-auth-express/pull/72

If you aren't, no worries, I will get this merged this weekend either way.

**Comment by connorjburton** [comment]
Resolved by #74 - sorry for the delay, it took me a long time to think of a nice way to achieve this without increasing the barrier to entry for the package.
