### ISSUE TITLE
Undefined body results in failing to match HMAC'S

### ISSUE THREAD

**Issue by alabdulaal** [connorjburton/hmac-auth-express#67]
Hi,

It looks like leaving the body ```undefined``` when generating a digest would result in generating a different HMAC than the source digest, thus returning an error with ```HMAC's did not match```

``` javascript 
// generating a digest with undefined body
generate("secret", "sha256", Date.now().toString(), "GET", "/api/order").digest("hex"); 
```

``` javascript 
// generating a digest with empty body
generate("secret", "sha256", Date.now().toString(), "GET", "/api/order", {}).digest("hex");
```

I'm not sure if this is the intended behavior, but it was mentioned in the readme that the body is not required.

**Comment by connorjburton** [comment]
Hi,

A request with no body and a request with an empty object as the body are two discrete requests and should generate different HMAC's. For example

```
POST /api/order HTTP/1.1
Host: example.com
```

is not the same as

```
POST /api/order HTTP/1.1
Host: example.com

{}
```

And therefore the generated HMAC should be different between those requests. There are 2 unit tests that cover both of these requests, see [this test for a request with no body](https://github.com/connorjburton/hmac-auth-express/blob/master/tests/unit.test.ts#L118) and [this test for a request with an empty object](https://github.com/connorjburton/hmac-auth-express/blob/master/tests/unit.test.ts#L289)

Please let me know if I have misunderstood your question.

**Comment by alabdulaal** [comment]
Yeah, I understand that. But, what threw me off was that I was sending a ```GET``` request, and a GET request doesn't contain a body.

**Comment by connorjburton** [comment]
[According to the HTTP/1.1 specification, `GET` requests with bodies are allowed (in the sense that it is not excluded).](https://datatracker.ietf.org/doc/html/rfc7231#page-25)

"A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request."

I don't believe it's our place to be opinionated on if a GET request should accept a request body or not, that should be the responsibility of the consumer of the package. This is not to say I believe you should send a request body with your GET requests, however the specification does not explicitly disallow it.

Thanks for taking your time to raise the issue.
